version: "3.8"

services:
  backend:
    build:
      context: ./atelier-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://anisoara:123%40.%40ateliercluster.adlz5.mongodb.net/atelierDB
      - NODE_ENV=development
      - SERVER_URL=http://localhost:5000
    volumes:
      - ./atelier-server:/app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./atelier-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./atelier:/app

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
