services:
  frontend:
    build:
      context: ./atelier-frontend
    ports:
      - "80:80"
  backend:
    build: ./atelier-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb+srv://anisoara:123.@ateliercluster.adlz5.mongodb.net/atelierDB
      PORT: 5000
      SERVER_URL: http://localhost:5000
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
